// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOGbV_PxMuxy0IaG4jvzlyQMkc4jHtWEM',
    appId: '1:473217744958:web:253a3a77cb56c8352b116f',
    messagingSenderId: '473217744958',
    projectId: 'delivery-app-16a04',
    authDomain: 'delivery-app-16a04.firebaseapp.com',
    databaseURL: 'https://delivery-app-16a04-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-16a04.appspot.com',
    measurementId: 'G-VLB9D1KC45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1J_MXJ-a6BH1USHW2JGEf273iZzrSNts',
    appId: '1:473217744958:android:80a0c874c54495c12b116f',
    messagingSenderId: '473217744958',
    projectId: 'delivery-app-16a04',
    databaseURL: 'https://delivery-app-16a04-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-16a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX-LHkEe-jraq59ZODAEzGY4EOeV8fKMc',
    appId: '1:473217744958:ios:065fa291752dbd012b116f',
    messagingSenderId: '473217744958',
    projectId: 'delivery-app-16a04',
    databaseURL: 'https://delivery-app-16a04-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-16a04.appspot.com',
    iosBundleId: 'ordeli.com.deliveryUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX-LHkEe-jraq59ZODAEzGY4EOeV8fKMc',
    appId: '1:473217744958:ios:065fa291752dbd012b116f',
    messagingSenderId: '473217744958',
    projectId: 'delivery-app-16a04',
    databaseURL: 'https://delivery-app-16a04-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-16a04.appspot.com',
    iosBundleId: 'ordeli.com.deliveryUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOGbV_PxMuxy0IaG4jvzlyQMkc4jHtWEM',
    appId: '1:473217744958:web:56dfae7e1bb5ffcf2b116f',
    messagingSenderId: '473217744958',
    projectId: 'delivery-app-16a04',
    authDomain: 'delivery-app-16a04.firebaseapp.com',
    databaseURL: 'https://delivery-app-16a04-default-rtdb.firebaseio.com',
    storageBucket: 'delivery-app-16a04.appspot.com',
    measurementId: 'G-CK68C9X4P8',
  );

}